Update setup.py
Updated use_scf_version line to be the same as emmet-core. 

I have no idea why, but using the previous version caused the following error on my machine:

LookupError: setuptools-scm was unable to detect version for.
...
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This doesn't change anything about functionality and just makes it match the other setup.py files.